### ISSUE TITLE
WP Recipe Maker creates unlinked h2

### ISSUE THREAD

**Issue by shay328** [maithemewp/mai-table-of-contents#7]
The WPRM Title adds an H2, but doesn't anchor down to it.

Example post with a recipe: https://wellnessmama.com/recipes/green-bean-casserole/

The title of the recipe: Healthy Green Bean Casserole Recipe

The WPRM is an H2 and is added to the Mai Table of Contents and includes a parameter to the URL (#healthy-green-bean-casserole-recipe) but doesn't anchor to the H2. https://wellnessmama.com/recipes/green-bean-casserole/#healthy-green-bean-casserole-recipe

(This TOC is inserted via block inside Mai Ads.)

<img width="1421" alt="Screen Shot on 2023-11-20 at 13-58-38" src="https://github.com/maithemewp/mai-table-of-contents/assets/43424037/26979bb6-adb7-4e0e-969c-43be9d58ac68">

**Comment by JiveDig** [comment]
This is working for me. It's also working for me now on WM as well hmmmm https://wellnessmama.com/recipes/green-bean-casserole/#h-the-best-green-bean-casserole-recipe

Maybe it was fixed in the last update?
